# Generated by Django 4.2.1 on 2023-12-15 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('country_city', models.CharField(max_length=100, verbose_name='Страна и город рождения')),
                ('address', models.CharField(blank=True, max_length=75, null=True, verbose_name='Адрес')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('nomination', models.CharField(choices=[('pop', 'Поп-музыка'), ('rock', 'Рок'), ('jazz', 'Джаз'), ('classical', 'Академический вокал'), ('folk', 'Фолк'), ('rap', 'Рэп')], max_length=20, verbose_name='Номинация')),
                ('age_category', models.CharField(choices=[('A1', 'A1 (6-9)'), ('A2', 'A2 (10-12)'), ('A3', 'A3 (13-15)')], max_length=20, verbose_name='Возрастная группа')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Введите корректный адрес электронной почты')], verbose_name='Электронная почта')),
                ('study_place', models.CharField(blank=True, max_length=50, null=True, verbose_name='Учебное заведение')),
                ('teacher_fio', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО преподавателя(руководителя)')),
                ('concertmaster_fio', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО концертмейстера')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='Время и дата заявки')),
                ('identity_document', models.FileField(blank=True, null=True, upload_to='identity_documents/', verbose_name='Удостоверение личности')),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='Квитанция об оплате')),
                ('participant_photo', models.ImageField(blank=True, null=True, upload_to='participant_photos/', verbose_name='Фотография участника')),
                ('audio_record', models.FileField(blank=True, null=True, upload_to='audio_records/', verbose_name='Прикрепленная аудиозапись')),
                ('song_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название произведения')),
                ('song_author', models.CharField(blank=True, max_length=20, null=True, verbose_name='Автор произведения')),
                ('duration_of_song', models.DurationField(blank=True, null=True, verbose_name='Длительность песни')),
            ],
        ),
    ]
